image: node:latest

stages:
  - install_dependencies
  - test
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - "**/node_modules/"
  policy: pull


install_dependencies:
  stage: install_dependencies
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - "**/node_modules/"
    policy: push
  script:
    - npm ci --no-progress --no-optional --no-audit --ignore-scripts --prefer-offline
  rules:
    - changes:
        - package-lock.json
    - if: '"True"'
      when: manual
      allow_failure: true
  tags:
  - opsmap

# job: test
test:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run test:unit
  tags:
    - opsmap
  artifacts:
    paths:
      - coverage


# job: pages
deploy:
  stage: deploy
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  tags:
    - opsmap
  only:
    - pages
