pages:
  image: node:latest
  stage: deploy
  script:
    - npm install --progress=false
    - npm run build
    - rm -rf public
    - mkdir public
    - mkdir public/data
    - cp -r dist/data/nigeria public/data
    - cp -r dist/img public
    - cp -r dist/js public
    - cp dist/index.html public/index.html
    - cp dist/favicon.ico public/favicon.ico
    - cp public/index.html public/404.html
  artifacts:
    expire_in: 1 day
    paths:
      - public
  tags:
    - opsmap
  only:
    - pages
