image: node:16

stages:
  - install_dependencies
  - test
  - deploy

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  # CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key:
    files:
      - package.json
  paths:
    - .npm
    # - cache/Cypress
    - node_modules
  policy: pull

# Install dependencies
install_dependencies:
  stage: install_dependencies
  cache:
    key:
      files:
        - package.json
    paths:
      - .npm
      # - cache/Cypress
      - node_modules
    policy: push
  script:
    - npm ci --no-progress --no-audit
  tags:
  - opsmap
  only:
  - pages

# Job: test
test:
  stage: test
  script:
    - npm run test:unit
  tags:
    - opsmap
  artifacts:
    paths:
      - coverage
  tags:
  - opsmap
  only:
  - pages

# job: build_and_deploy
pages:
  stage: deploy
  script:
    - npm run build-gitlab
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
    - cp public/index.html public/404.html
  artifacts:
    expire_in: 1 day
    paths:
      - public
  tags:
    - opsmap
  only:
    - pages
