stages:
  - build
  - test
  - deploy


# Not sure about this.
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  # CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# Build stage: use to cache for test then deploy to pages
build:
  stage: build
  script:
    - npm install --progress=false
    - npm run build

  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

# Test stage: Run the test for every push
test:
  stage: test
  cache:
    key:
      files:
        - package.json
    paths:
      - .npm
      - cache/Cypress
      - node_modules
  script:
    - npm ci --progress=false
    - npm run test:unit

# Deploy to gitlab pages
pages:
  image: node:latest
  stage: deploy
  script:
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  tags:
    - opsmap
  only:
    - pages
