pages:
  image: node:latest
  stage: deploy
  script:
    - npm install --progress=false
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
    - cp public/index.html public/404.html
  artifacts:
    expire_in: 1 day
    paths:
      - public
  tags:
    - opsmap
  only:
    - master

test:
  image: node:latest
  stage: test
  script:
    - npm install --progress=false
    - npm run build
    - rm -rf test
    - mkdir test
    - cp -r dist/* test
    - cp test/index.html test/404.html
  artifacts:
    paths:
      - test
  rules:
    - if: '$CI_COMMIT_BRANCH == "preview"'
  tags:
  - opsmap

