image: node:16

# stages
stages:
  - install_dependencies
  - test
  - deploy

# variables
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

# cache
cache:
  key:
    files:
      - package.json
  paths:
    - .npm
    - node_modules
  policy: pull

# install dependencies
install_dependencies:
  stage: install_dependencies
  cache:
    key:
      files:
        - package.json
    paths:
      - .npm
      - node_modules
    policy: push
  script:
    - npm ci --no-progress --no-audit --legacy-peer-deps
  tags:
    - opsmap
  rules:
    - if: $CI_COMMIT_BRANCH == "release/deploy-gitlab-pages"
    - if: $CI_COMMIT_BRANCH == "release/deploy-docker"
      when: always
    - when: manual

# job: test
test:
  needs: ["install_dependencies"]
  stage: test
  script:
    - npm run test:unit
  tags:
    - opsmap
  artifacts:
    paths:
      - coverage

# job: build_and_deploy
pages:
  needs: ["test"]
  stage: deploy
  variables:
    VUE_APP_RIDL_TOKEN: $VUE_APP_RIDL_TOKEN
  script:
    - npm run build-opsmap -- $CI_OPSMAP_NAME
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
    - cp public/index.html public/404.html
  artifacts:
    expire_in: 1 day
    paths:
      - public
  tags:
    - opsmap
  only:
    - release/deploy-gitlab-pages

# job: build docker image and deploy
docker-build:
  # Official docker image.
  image: docker:stable
  stage: deploy
  services:
    - docker:19.03.0-dind
  before_script:
    - apk add git
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # opsmap list as --build-arg
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$(git describe --tags --abbrev=0)" . --build-arg opsmaps="brazil burkina-faso ethiopia moldova nigeria romania showcase slovakia somalia sudan ukraine yemen"
    - docker tag "$CI_REGISTRY_IMAGE:$(git describe --tags --abbrev=0)" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:$(git describe --tags --abbrev=0)"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  tags:
    - dind
  only:
    - release/deploy-docker
