image: node:16

stages:
  - install_dependencies
  - test
  - deploy

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

cache:
  key:
    files:
      - package.json
  paths:
    - .npm
    - node_modules
  policy: pull

# Install dependencies
step_install_dependencies:
  stage: install_dependencies
  cache:
    key:
      files:
        - package.json
    paths:
      - .npm
      - node_modules
    policy: push
  script:
    - npm ci --no-progress --no-audit --legacy-peer-deps
  tags:
    - opsmap
  rules:
    - if: $CI_COMMIT_BRANCH == "pages"
      when: always
    - if: $CI_COMMIT_BRANCH != "pages"
      when: manual

# Job: test
step_test:
  needs: ["step_install_dependencies"]
  stage: test
  script:
    - npm run test:unit
  tags:
    - opsmap
  artifacts:
    paths:
      - coverage

# job: build_and_deploy
step_pages:
  needs: ["step_test"]
  stage: deploy
  script:
    - npm run build-gitlab
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
    - cp public/index.html public/404.html
  artifacts:
    expire_in: 1 day
    paths:
      - public
  tags:
    - opsmap
