export const COLOR_PRIMARY = "#333333";
export const COLOR_SELECTED = "#EC6B4D";

export type TKColor = string;

export enum TKColors {
  ACCENT = "#1B657C",
  BACKGROUND = "#ffffff",
  BACKGROUND_SECONDARY = "#F5F3E8",
  DARK_GREY = "#2C2C2C",
  SECONDARY = "#999999",
  SITE_OCCUPATION_OK = "#A8D08D",
  SITE_OCCUPATION_WARNING = "#FFC000",
  SITE_OCCUPATION_DANGER = "#FF0000",
  SITE_OCCUPATION_CRITICAL = "#C00000",
  SITE_OCCUPATION_UNDEFINED = "#999999",
  WHITE = "#ffffff"
}
